import type { Metadata } from "next";
import { useState } from "react";
import Topbar from "../components/topbar";
import Side from "../components/side";
import styles from "../styles/dashboardLayout.module.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const [hideSideBar, setHideSideBar] = useState(true);
  const [animate, setAnimate] = useState(false);

  const toggleSidebar = () => {
    if (!hideSideBar) {
      setAnimate(true);

      setTimeout(() => {
        setHideSideBar(true);
        setAnimate(false);
      }, 300);
    } else {
      setHideSideBar(false);
      setAnimate(true);
    }
  };

  return (
    <div className={styles.RootWrapper}>
      <Topbar hideSideBar={hideSideBar} toggleSidebar={toggleSidebar} />
      <div className={styles.Wrapper}>
        <Side
          hideSideBar={hideSideBar}
          animate={animate}
          toggleSidebar={toggleSidebar}
        />
        <main className={styles.MainWrapper}>{children}</main>
      </div>
    </div>
  );
}
